### ISSUE TITLE
navigate and go back between 2 different stacks

### ISSUE THREAD

**Issue by adirzoari** [himelbrand/mobx-react-navigation-store#2]
I'm trying to navigate between two different stack but I little stacked with it.
 Main stack
```
const hydrate = create({
    storage: AsyncStorage,
})

let hydrated = false
const stores = { NavigationStore, UserStore, ProductStore }

const Routes = StackNavigator('Main',
    {
        Login: { screen: Login }, 
        Home: { screen: Home },
        Profile: { screen: Profile },
        WishList: { screen: WishList },
        Search: { screen: Search },
    }, {

        headerMode: 'none',
        lazy: false,
        initialRouteName: 'Home'
    }
)



hydrate('user', UserStore).then(() => {
    UserStore.doneHydrating();
})


const result = hydrate('Nav', NavigationStore).then(() => {
    NavigationStore.setNavigators({
        Main: {
            type: 'stack',
            parent: null,
            shouldPersist: false,
            routes: ['Login', 'Home', 'Profile', 'WishList', 'Search'],
            initRoute: 'Home'
        },
        HomeRoutes: {
            type: 'stack',
            parent: 'Main',
            shouldPersist: false,
            routes: ['Dashboard','MainCategories','SecondCategories'],
            initRoute: 'Dashboard'
        },


    }, {
            initialNavigatorName: 'Main',
            order: ['Main','HomeRoutes']
        })
    !NavigationStore.ActiveNavigator && NavigationStore.setActiveNavigator('Main')
    setTimeout(() => NavigationStore.doneHydrating(), 1000)
    NavigationStore.StartedStoreHydration()
}).catch(error => console.log(error))

```

HomeRoutes

```

const Routes = StackNavigator('HomeRoutes',
    {
        Dashboard: { screen: Dashboard, title: 'Dashboard' },
        MainCategories: { screen: MainCategories, title: 'MainCategories' },
        SecondCategories: { screen: SecondCategories, title: 'SecondCategories' },


    }, {
        
        headerMode: 'none',
        lazy: false,
        initialRouteName: 'Dashboard'
    }
)
```

I defined the init route to be the HomeRoutes to route 'Dashboard', 
when I try to navigate from Dashboard to Search screen( Search is out this stack)
I write 
`this.props.NavigationStore.navigate({routeName:'Search'})`
and nothing is happened.
the only option i succeed it to navigate is to MainCategories or secondCategories.

in addition, if I navigate from Dashboard to SecodCategories and I'm trying to goBack by this line
`this.props.NavigationStore.goBack()`
the currentRoute(by the console log print is changed) but the screen not really changed, it stay in same screen 'secondCategories', but only the currentRoute, the name has changed.

other issue is,when I exist from app and enter again, it still show me the last screen I visited, even the shouldPersist is false.

**Comment by himelbrand** [comment]
@adirzoari first of all try to change 
this.props.NavigationStore.goBack()
to 
this.props.NavigationStore.goBack(true)
this is about the go back issue,

about the other issue I don't understand completely.

so if you could post more info about this issue, it will be great.

if what I suggested for the goBack issue doesn't help open a separate issue for it.

thanks

**Comment by adirzoari** [comment]
Hey,
thank you for quick response.
I tried your suggestion, but still goBack stay in same screen but the currentRoute name changed. 
I guess it's because it's not navigate correctly for me.
about the other issues, I'm trying explain myself  again.
I init the first screen to be 'Dashboard' (in HomeRoutes Stack).
when i try to navigate from 'Dashboard' to 'Search', nothing happened. I stay in some screen.
maybe it's because it's different stacks..

the second issue, 'shouldPersist' equal to false not really working for me. if I exit from app and come back again, it still show me the last screen I have visited..

**Comment by himelbrand** [comment]
@adirzoari about 'shouldPersist' check that you set it false in all the places you need for your required behavior.
this should not be an issue as far as I know.
about the original issue, i'm closing it and try what I told you in private since It doesn't look like an issue with the package buy with your use of it.

if it won't work open an issue again with more specific details please
